name: flourish_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  rxdart: ^0.27.7
  quiver: ^3.2.1
  marquee: ^2.2.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  flutter_audio_waveforms: ^1.2.1+8
  card_swiper: ^3.0.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_ui_auth: ^1.15.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  firebase_storage: ^12.1.1
  uuid: ^4.4.2
  intl: ^0.19.0
  image_picker_web: ^4.0.0

  universal_html: ^2.2.4
  chat_gpt_sdk:
    git:
      url: https://github.com/daniel360kim/chat_gpt_sdk.git
      ref: main
  flutter_math_fork: ^0.7.2
  flutter_markdown: ^0.7.3
  lottie: ^3.1.2
  dio: ^5.5.0+1
  universal_io: ^2.2.2
  logger: ^2.4.0
  flutter_stripe: ^11.0.0
  shimmer: ^3.0.0




  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI/SegoeUI-Regular.ttf
        - asset: assets/fonts/SegoeUI/SegoeUI-Bold.ttf

  uses-material-design: true
  assets:
    - assets/background/
    - assets/scenes/
    - assets/brand/
    - assets/animations/