name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2.2.1
        with:
          channel: beta
          cache: true
      - uses: actions/checkout@v2
      - run: flutter build web --no-tree-shake-icons
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLOURISH_WEB_FA343 }}
          channelId: live
          projectId: flourish-web-fa343
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
